sitename = "Francesco Maida"
defaultColor = "light" # set color mode: dark, light, auto

# Setting it to 'auto' applies the color scheme based on the visitor's device color preference.If you don't specify anything, ignore this parameter, or leave it blank,
# the default value is set to 'auto'.
# You can take a look at layouts/index.html for more information.
description = "Vivo e lavoro a Venezia. Sono uno sviluppatore di siti e gestionali di giorno, ed aspirante indie developer di notte. Tipo Dr. Jekyll e Mr. Hyde, ma meno figo."

mainSections = ["blog", "tutorial", "recensioni"]
toc = true # set to false to disable table of contents 'globally'
goToTop = true # set to false to disable 'go to top' button
additionalScripts = ['js/custom.js', 'js/custom-2.js']

# Will try to load 'assets/js/custom.js' and 'assets/js/custom-2.js'.
# Your custom scripts will be concatinated to one file `custom.js`.
# When building for production it will be minified.
# The file `custom.js` is loaded on each page (before body tag ends).
dateFormat = "2 Jan" # default date format used on various pages

# See https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference for available date formats.
rssFeedDescription = "summary" # available options: 1) summary 2) full

# summary - includes a short summary of the blog post in the RSS feed. Generated using Hugo .Summary .
# full - includes full blog post in the RSS feed. Generated using Hugo .Content .
# By default (or if nothing is specified), summary is used.

[author]
    avatar = "avatar.jpg" # put the file in assets folder; also ensure that image has same height and width
  
    # Note: image is not rendered if the resource(avatar image) is not found. No error is displayed.
    intro = "Francesco Maida"
    name = "Francesco Maida"
    description = "Vivo e lavoro a Venezia. Sono uno sviluppatore di siti e gestionali di giorno, ed aspirante indie developer di notte. Tipo Dr. Jekyll e Mr. Hyde, ma meno figo."

# Allow to override webmanifest options
[webmanifest]
    name = "Francesco Maida" # will use "params.sitename" or "title" by default
    short_name = "Francesco Maida" # same as name
    start_url = "/" # will use homepage url by default
    theme_color = "#fff" # default is "#434648" (base color of text). Also will override html `<meta name="theme-color" />`
    background_color = "#fff" # by default depend on "params.defaultColor" for "light" or "auto" will be set to "#fff" for dark will be "#131418" (color of dark mode background)
    display = "standalone"

###################################################################

# Allow to override `browserconfig.xml` params (configuration for windows embeded browsers)
[browserconfig]
    TileColor = "#2d89ef" # default windows 10 blue tile color

[[socialIcons]]
    name = "github"
    url = "https://github.com/fmaida"

[[socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/fmaida"

[[socialIcons]]
    name = "itchio"
    url = "https://cesco.itch.io"

[[socialIcons]]
    name = "mastodon"
    url = "https://livellosegreto.it/@cesco"

[[socialIcons]]
    name = "email"
    url = "mailto:museo05_vasto@icloud.com"

#[[socialIcons]]
#   name = "Rss"
#   url = "index.xml"