[[main]]
    # The page reference (pageRef) is useful for menu highlighting
    # When pageRef is set, setting `url` is optional; it will be used as a fallback if the page is not found.
    pageRef="/"
    name = 'Home'
    url = '/'
    weight = 10

[[main]]
    pageRef="blog"
    name = "Blog"
    url = "/blog/"
    weight = 20

[[main]]
  name = "Mastodon"
  title = "Seguimi su Mastodon"
  url = "https://livellosegreto.it/@cesco"
  rel = "me"
  weight = 30
  [main.params]
    icon = "mastodon"    
    showName = false
    target = "_blank"

[[main]]
  name = "YouTube"
  title = "Seguimi su YouTube"
  url = "https://www.youtube.com/@retroblogit"
  rel = "me"
  weight = 40
  [main.params]
    icon = "youtube"
    showName = false
    target = "_blank"
