# set markup.highlight.noClasses=false to enable code highlight

[highlight]
    noClasses = false

[goldmark.renderer]
    unsafe = true

[tableOfContents]
    startLevel = 2 # ToC starts from H2
    endLevel = 4 # ToC ends at H4
    ordered = false # generates <ul> instead of <ol>